### ISSUE TITLE
提案: ライセンスの明示

### ISSUE THREAD

**Issue by kuzuha** [sharin-sushi/V-Kara-Lists#169]
慣習的に LICENSE ファイルをトップレベルに配置し、ソフトウェアのライセンスを明示します
github では LICENSE ファイルからソフトウェアのライセンス種別を判断し、その内容がどのようなものかを表示し、利用者の判断をサポートする仕組みもあります
例: https://github.com/gin-gonic/gin/blob/master/LICENSE

私個人としてもぜひこのソフトウェアを利用したいと思いましたので、今回の提案をさせていただきます。

**Comment by sharin-sushi** [comment]
@kuzuha 様
ご提案いただきありがとうございます！

昨日、
> 私個人としてもぜひこのソフトウェアを利用したいと思いましたので、今回の提案をさせていただきます。
を拝読し、とても嬉しかったです。まだ内定も、ユーザーが定着した様子も無いのに、少し報われた気がして目が滲みました笑

さて、ライセンスについてですが、全くの無知でした。
[これ](https://qiita.com/Tatamo/items/ae7bf4878abcf0584291)を流し読みした程度ですが、「OSSとして他者を巻き込んで開発するなら必要な取り組み」という解釈を得ました。
合っていますでしょうか？

私としてもV-Karaの開発スピードも品質も向上させたく、他人のアドバイスは積極的に受け入れたいと思っています。
ただ、今は未経験のポートフォリオとしての役割もあるので、直ぐにとは思っていません。

また、現在はV-karaのバグ修正や、求人応募後にお返事いただいた企業様への対応に追われており、中々調べたり実装したりする時間もありません。

上述の認識で合っていれば、少し優先度を下げ、来週末を目処に対応させていただきたいと考えています。
(もしかしたら実装は簡単かも知れませんが、理解してないライセンスのことを実装するのもどうかと思うので)

もしも、再度ご意見をいただけましたら、誠に幸いです。

しゃり

**Comment by sharin-sushi** [comment]
@kuzuha 

申し訳ありません。
ライセンスについて対応を延期させていただきます。

企業選考で製作課題があり、期限内(~3/21)はそちらに集中したく思います。
追ってご連絡させていただきます。

**Comment by sharin-sushi** [comment]
@kuzuha 様

Xでのやり取りを含め大変お世話になりました。
MITライセンスを導入いたしました。

今後もお気づきのことがあれば何でもご教授いただけますと幸いです。
